version: '3.8'

services:
  aula-sistemas-backend:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      # Para desenvolvimento, monte o código fonte (opcional)
      - ./appsettings.Development.json:/app/appsettings.Development.json:ro
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge